site_name: Applied Deep Learning
site_url: https://www.data-mining.co.nz/applied-deeplearning/
site_description: Documentation for Applied Deep Learning.
theme:
    name: readthedocs
markdown_extensions:
    - toc:
        baselevel: 3
nav:
  - 'Home': index.md
  - 'Prerequisites': prerequisites.md
  - 'Image classification':
    - 'Introduction': image_classification/index.md
    - 'Annotate': image_classification/annotate.md
    - 'Framework':
      - 'wai.pytorchimageclass': image_classification/wai.pytorchimageclass.md
      - 'wai.tfimageclass': image_classification/wai.tfimageclass.md
      - 'wai.tflite_model_maker': image_classification/wai.tflite_model_maker.md
  - 'Object detection':
    - 'Introduction': object_detection/index.md
    - 'Annotate': object_detection/annotate.md
    - 'Framework':
      - 'MMDetection': object_detection/mmdetection.md
      - 'wai.tflite_model_maker': object_detection/wai.tflite_model_maker.md
  - 'Instance segmentation':
    - 'Introduction': instance_segmentation/index.md
    - 'Annotate': instance_segmentation/annotate.md
    - 'Framework':
      - 'Detectron2': instance_segmentation/detectron2.md
  - 'Image segmentation':
    - 'Introduction': image_segmentation/index.md
    - 'Annotate': image_segmentation/annotate.md
    - 'Framework':
      - 'Image Segmentation Keras': image_segmentation/image-segmentation-keras.md
