site_name: Applied Deep Learning
site_url: https://www.data-mining.co.nz/applied-deep-learning/
site_description: Documentation for Applied Deep Learning.
repo_url: https://github.com/waikato-datamining/applied-deep-learning
theme:
    name: readthedocs
plugins:
    # https://github.com/soulless-viewer/mkdocs-video
    - mkdocs-video
    # https://github.com/timvink/mkdocs-table-reader-plugin
    - search
    - table-reader
markdown_extensions:
    - toc:
        baselevel: 3
nav:
  - 'Home': index.md
  - 'Prerequisites': prerequisites.md
  - 'Image classification':
    - 'Introduction': image_classification/index.md
    - 'Annotate': image_classification/annotate.md
    - '» MMClassification': image_classification/mmclassification.md
    - '» wai.tfimageclass': image_classification/wai.tfimageclass.md
  - 'Object detection':
    - 'Introduction': object_detection/index.md
    - 'Annotate': object_detection/annotate.md
    - '» MMDetection': object_detection/mmdetection.md
    - '» Yolov5': object_detection/yolov5.md
  - 'Instance segmentation':
    - 'Introduction': instance_segmentation/index.md
    - 'Annotate': instance_segmentation/annotate.md
    - '» Detectron2': instance_segmentation/detectron2.md
  - 'Image segmentation':
    - 'Introduction': image_segmentation/index.md
    - 'Annotate': image_segmentation/annotate.md
    - '» Image Segmentation Keras': image_segmentation/image-segmentation-keras.md
    - '» MMSegmentation': image_segmentation/mmsegmentation.md
