site_name: Applied Deep Learning
site_url: https://www.data-mining.co.nz/applied-deep-learning/
site_description: Documentation for Applied Deep Learning.
repo_url: https://github.com/waikato-datamining/applied-deep-learning
edit_uri: edit/main/docs/
theme:
    name: readthedocs
markdown_extensions:
    - toc:
        baselevel: 2
        permalink: "#"
plugins:
    - search
    # https://github.com/soulless-viewer/mkdocs-video
    - mkdocs-video
    # https://github.com/timvink/mkdocs-table-reader-plugin
    - table-reader
nav:
  - 'Home': index.md
  - 'Prerequisites': prerequisites.md
  - 'Image classification':
    - 'Introduction': image_classification/index.md
    - 'Annotate': image_classification/annotate.md
    - 'Frameworks': image_classification/frameworks.md
  - 'Object detection':
    - 'Introduction': object_detection/index.md
    - 'Annotate': object_detection/annotate.md
    - 'Frameworks': object_detection/frameworks.md
  - 'Instance segmentation':
    - 'Introduction': instance_segmentation/index.md
    - 'Annotate': instance_segmentation/annotate.md
    - 'Frameworks': instance_segmentation/frameworks.md
  - 'Image segmentation':
    - 'Introduction': image_segmentation/index.md
    - 'Annotate': image_segmentation/annotate.md
    - 'Frameworks': image_segmentation/frameworks.md
